baseURL = "https://www.next-book.info"
defaultContentLanguage = "cs"
title = "next-book"
disableKinds = ["taxonomyTerm", "taxonomy"]
relativeurls = true

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.cs]
    contentDir = "content"
    languageName = "Česky"
    weight = 2
    [languages.cs.params]
  [languages.en]
    contentDir = "content-en"
    languageName = "English"
    weight = 1
    [languages.en.params]

